/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTable: typeof import('./src/components/shared/AppTable.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    CheckInOutSidebar: typeof import('./src/components/layout/CheckInOutSidebar.vue')['default']
    ClientCard: typeof import('./src/components/ClientCard.vue')['default']
    CountryPhoneInput: typeof import('./src/components/shared/CountryPhoneInput.vue')['default']
    DashboardCalendar: typeof import('./src/components/DashboardCalendar.vue')['default']
    DashboardLayout: typeof import('./src/components/layout/DashboardLayout.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FilterCard: typeof import('./src/components/FilterCard.vue')['default']
    GlobalButton: typeof import('./src/components/shared/GlobalButton.vue')['default']
    GlobalTextField: typeof import('./src/components/shared/GlobalTextField.vue')['default']
    GreetingCard: typeof import('./src/components/GreetingCard.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    NotificationDrawer: typeof import('./src/components/NotificationDrawer.vue')['default']
    RosterCalendar: typeof import('./src/components/RosterCalendar.vue')['default']
    RosterFilterCard: typeof import('./src/components/RosterFilterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleModal: typeof import('./src/components/ScheduleModal.vue')['default']
    SchedulesCard: typeof import('./src/components/SchedulesCard.vue')['default']
    SearchBar: typeof import('./src/components/layout/SearchBar.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    VuetifyExample: typeof import('./src/components/VuetifyExample.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
