/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTable: typeof import('./src/components/shared/AppTable.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ClientCard: typeof import('./src/components/ClientCard.vue')['default']
    DashboardCalendar: typeof import('./src/components/DashboardCalendar.vue')['default']
    DashboardLayout: typeof import('./src/components/layout/DashboardLayout.vue')['default']
    FilterCard: typeof import('./src/components/FilterCard.vue')['default']
    GreetingCard: typeof import('./src/components/GreetingCard.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulesCard: typeof import('./src/components/SchedulesCard.vue')['default']
    SearchBar: typeof import('./src/components/layout/SearchBar.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    VuetifyExample: typeof import('./src/components/VuetifyExample.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
